name: wimdrive
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.3.10"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # lottie: ^2.2.0
  flutter_inappwebview: ^5.7.2+3
  url_launcher: ^6.1.7
  get: ^4.6.5
  internet_connection_checker: ^1.0.0+1
  app_settings: ^4.2.0

  # flutter_native_splash: ^2.2.17
  rename: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"

flutter_native_splash:
  color: "#0A85ED"
  image: assets/wim_Logo.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
